In [1]:
import numpy as np

In [60]:
matrix = [[5,3,8,9,4,1,3,-2],
[4,6,0,3,6,4,2,1],
[4,-5,3,1,9,5,6,6],
[4,-5,3,1,9,5,6,6],
[3,7,5,3,2,8,9,4],
[5,3,-3,6,3,2,8,0],
[5,7,5,3,3,-9,2,2],
[0,4,3,2,5,7,5,4]]


In [61]:
matrix = np.array(matrix)

In [62]:
lists, items = matrix.shape

In [102]:
matrix[lists-lists,:items-1]

array([5, 3, 8, 9, 4, 1, 3])

In [105]:
matrix[:lists-2,items-1]

array([-2,  1,  6,  6,  4,  0])

In [106]:
matrix[lists-2,2:items]

array([ 5,  3,  3, -9,  2,  2])

In [108]:
matrix[3:lists-1,items-7]

array([-5,  7,  3,  7])

In [114]:
matrix[lists-6,1:items-3]

array([-5,  3,  1,  9])

In [110]:
matrix[2:lists-4,items-3]

array([5, 5])

In [113]:
matrix[lists-4,3:items-2]    

array([3, 2, 8])

In [106]:
matrix[lists-2,2:items]

array([ 5,  3,  3, -9,  2,  2])

In [113]:
matrix[lists-4,3:items-2]    

array([3, 2, 8])

In [114]:
matrix[lists-6,1:items-3]

array([-5,  3,  1,  9])

In [102]:
matrix[lists-lists,:items-1]

array([5, 3, 8, 9, 4, 1, 3])

In [117]:
matrix[:6,7]

array([-2,  1,  6,  6,  4,  0])

In [116]:
matrix[2:4,5]

array([5, 5])

In [115]:
matrix[3:7,1]

array([-5,  7,  3,  7])